# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 03:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmigoRosa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=400, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=20)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('contato', models.CharField(max_length=20)),
                ('data_nascimento', models.CharField(max_length=20, verbose_name='Data de nascimento')),
                ('email', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=200)),
                ('cpf', models.CharField(help_text='Apenas números', max_length=15, verbose_name='CPF')),
                ('rg', models.CharField(max_length=15, verbose_name='RG')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da paciente')),
                ('local_palestra', models.CharField(blank=True, max_length=200, verbose_name='Onde assistiu a palestra do IMAMA')),
                ('data_nascimento', models.DateField(help_text='dd/mm/aaaa', verbose_name='Data de nascimento')),
                ('sexo', models.CharField(max_length=10)),
                ('etnia', models.CharField(max_length=20)),
                ('telefone', models.CharField(help_text='(99) 9999999999', max_length=20)),
                ('celular', models.CharField(blank=True, help_text='(99) 9999999999', max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=400, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=50)),
                ('contato_nome', models.CharField(blank=True, max_length=200, verbose_name='Pessoa para contato')),
                ('contato_telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone do contato')),
                ('cpf', models.CharField(help_text='Apenas números', max_length=20, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('amigo_rosa', models.CharField(max_length=200, verbose_name='Navegador')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacoes', models.TextField(verbose_name='Observações')),
                ('data_entrevista', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data da entrevista e mamografia PoA Rural')),
                ('UAB_referencia', models.CharField(blank=True, max_length=200, verbose_name='Unidade de Atenção Básica de Referência')),
                ('cartao_sus', models.CharField(blank=True, max_length=20, verbose_name='Nº Cartão SUS')),
                ('sistema_saude', models.CharField(blank=True, max_length=200, verbose_name='Utiliza outro tipo de sistema de saúde')),
                ('beneficio_governo', models.CharField(blank=True, max_length=20, verbose_name='Recebe algum benefício do governo')),
                ('qtdade_filhos', models.CharField(blank=True, max_length=20, verbose_name='Estado civil')),
                ('estado_civil', models.CharField(blank=True, max_length=20, verbose_name='Nº de filhos')),
                ('idade_filhos', models.CharField(blank=True, max_length=20, verbose_name='Idade dos filhos')),
                ('profissao', models.CharField(blank=True, max_length=50, verbose_name='Profissão')),
                ('exerce_profissao', models.CharField(blank=True, max_length=20, verbose_name='Atualmente exerce a profissão')),
                ('data_menarca', models.DateTimeField(blank=True, verbose_name='Data da menarca (1ª menstruação)')),
                ('menopausa', models.CharField(blank=True, max_length=20, verbose_name='Menopausa')),
                ('data_menopausa', models.DateTimeField(blank=True, verbose_name='Desde quando')),
                ('reposicao_hormonal', models.CharField(blank=True, max_length=20, verbose_name='Reposição hormonal')),
                ('data_reposicao_hormonal', models.DateTimeField(blank=True, verbose_name='Há quanto tempo')),
                ('local_trabalho', models.CharField(blank=True, max_length=200, verbose_name='Onde trabalha')),
                ('sustenta_familia', models.CharField(blank=True, max_length=20, verbose_name='É responsável pelo sustento da família')),
                ('pessoas_familia', models.CharField(blank=True, max_length=2, verbose_name='Quantas pessoas moram com você')),
                ('escolaridade', models.CharField(blank=True, max_length=40)),
                ('motivos_servico_saude', models.TextField(blank=True, verbose_name='Costuma procurar o serviço de saúde para')),
                ('ultima_consulta_ginecologista', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data da última consulta com ginecologista')),
                ('auto_exame', models.CharField(blank=True, max_length=20, verbose_name='Costuma examinar suas próprias mamas')),
                ('exame_profissional', models.CharField(blank=True, max_length=20, verbose_name='Suas mamas são apalpadas por profissionais de saúde')),
                ('data_mamografia', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data da mamografia mais recente')),
                ('conclusao_laudo_mamografia', models.TextField(blank=True, verbose_name='Conclusão do laudos da mamografia mais recente')),
                ('data_outros_exames', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Outros exames das mamas (data)')),
                ('conclusao_laudo_outros_exames', models.TextField(blank=True, verbose_name='Conclusão do laudo dos outros exames')),
                ('orientacoes_exames', models.TextField(blank=True, verbose_name='Quais orientações recebeu sobre os resultados dos exames, por quem e quando')),
                ('alteracao_mama', models.CharField(blank=True, max_length=20, verbose_name='Percebeu alguma alteração na mama?')),
                ('familiares_cancer_mama', models.CharField(blank=True, max_length=20, verbose_name='Tem familiares com câncer de mama')),
                ('cirurgia_mamas', models.CharField(blank=True, max_length=20, verbose_name='Já fez alguma cirurgia nas mamas')),
                ('tipo_cirurgia_mamas', models.TextField(blank=True, verbose_name='Tipo de cirugia')),
                ('observacoes_entrevista', models.TextField(blank=True, verbose_name='Observações')),
                ('imama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
